#!/usr/bin/env bash

function main {
  local shome="$(cd -P -- "${BASH_SOURCE%/*}/.." && pwd -P)"

  stty -echo
  trap 'stty echo' EXIT

  coproc tail { tail -f "$shome/log/console.log"; }
  exec 4<&${tail[0]}

  IFS=
  accum=
  d=
  while true; do 
    if [[ -n "${accum:-}" ]]; then
      stty echo
      if read -p '#immanent > ' -r -e -i "$accum" d; then
        accum="${d}"
        echo "privmsg #immanent :$accum" > "$shome/tmp/input.tmp"
        accum=
        while [[ -f "$shome/tmp/input.txt" ]]; do
          sleep 1
        done
        mv "$shome/tmp/input.tmp" "$shome/tmp/input.txt"
      fi
    else
      stty -echo
      if read -t 1 -N 1 -r -s d; then
        accum="${d}"
        continue
      fi

      while true; do
        if read -t 1 -u 4 -r console; then
          echo "$console"
        else
          break
        fi
      done
    fi
  done

}

source sub "$BASH_SOURCE" "$@"
