#!/usr/bin/env bash

mkdir -p "$shome/log"

function console {
  local msg_console="$1"; shift

  echo "$msg_console" 1>>"$shome/log/console.log"
}

function reply {
  local msg_server="$1"; shift
  local msg_source="${1:-}"

  echo "$msg_server"

  echo "SENT: $msg_server" 1>&2
  {
    echo
    echo "FROM: $msg_source"
    echo "SENT: $msg_server"
  } 1>>"$shome/log/sent.log"
}

function on_timeout {
  if [[ -f "$shome/tmp/input.txt" ]]; then
    cat "$shome/tmp/input.txt"
    cat "$shome/tmp/input.txt" >> "$shome/log/sent.log"
    rm -f "$shome/tmp/input.txt"
  else
    true
  fi
}

function on_bot {
  local nm_handler="on_${IRC_COMMAND,,}"
  if [[ "$(type -t "${nm_handler}")" == "function" ]]; then
    "$nm_handler"
    case "${nm_handler}" in
      on_ping)
        return
        ;;
    esac
  else
    on_weird
  fi

  on_log
}

function on_weird {
  case "${IRC_COMMAND}" in
    $RPL_ENDOFMOTD)
      reply "JOIN ${nm_channel}" "$line"
      ;;
  esac
}

function on_quit {
  local pid_irc="${irc_PID:-}"

  if [[ -n "$pid_irc" ]]; then
    kill "${pid_irc}"
    wait "${pid_irc}"
  fi
  exit 1
}

function on_error {
  on_quit
}

function on_log {
  {
    echo
    echo "IRC_LINE    ${line}"
    echo "IRC_PREFIX  ${IRC_PREFIX:-}"
    echo "IRC_COMMAND ${IRC_COMMAND:-}"
    echo "IRC_PARAMS  ${IRC_PARAMS[*]}"
    echo "IRC_PARAMS0 ${IRC_PARAMS[0]:-}"
    echo "IRC_PARAMS1 ${IRC_PARAMS[1]:-}"
    echo "IRC_PARAMS2 ${IRC_PARAMS[2]:-}"
    echo "IRC_TEXT    ${IRC_TEXT:-}"
    echo "IRC_CHANNEL ${IRC_CHANNEL:-}"
    echo "IRC_SENDER  ${IRC_SENDER:-}" 
  } 1>>"$shome/log/debug.log"
}

function on_ping {
  irc_ping
}

function on_privmsg {
  if [[ "${IRC_CHANNEL:-}" == "${IRC_SENDER:-}" ]]; then
    case "${IRC_PARAMS[1]:-}" in
      "join #"*)
        reply "JOIN ${IRC_PARAMS[1]#* }" "$line"
        ;;
      "part #"*)
        reply "PART ${IRC_PARAMS[1]#* }" "$line"
        ;;
    esac
    console "${IRC_SENDER} ${IRC_TEXT}"
  else
    console "${IRC_CHANNEL:-} ${IRC_SENDER} ${IRC_TEXT}"
  fi

}

function on_notice {
  if [[ "${IRC_CHANNEL:-}" == "${IRC_SENDER:-}" ]]; then
    console "*** ${IRC_SENDER} ${IRC_TEXT}"
  else
    console "*** ${IRC_CHANNEL:-} ${IRC_SENDER} ${IRC_TEXT}"
  fi

}

function on_cap {
  case "${IRC_PARAMS[1]:-}" in
    LS)
      reply "CAP REQ :multi-prefix sasl"
      ;;
    ACK)
      reply "AUTHENTICATE PLAIN"
      ;;
    NAK)
      on_quit
      ;;
    LIST)
      reply "CAP END"
      ;;
  esac
}

function on_authenticate {
	true
}

# RPL_LOGGEDIN
function on_900 {
	reply "CAP END"
}

# RPL_LOGGEDOUT
function on_901 {
	reply "CAP END"
}

# ERR_NICKLOCKED
function on_902 {
	reply "CAP END"
}

# RPL_SASLSUCCESS
function on_903 {
	reply "CAP END"
}

# ERR_SASLFAIL
function on_904 {
	on_quit
}

# ERR_SASLTOOLONG
function on_905 {
	reply "CAP END"
}

# ERR_SASLABORTED
function on_906 {
	on_quit
}

# ERR_SASLALREADY
function on_907 {
	reply "CAP END"
}

# RPL_SASLMECHS
function on_908 {
	reply "CAP END"
}
