#!/usr/bin/env bash

function on_bot {
	case "${IRC_COMMAND}" in
		PING)
			echo "PONG ${IRC_PARAMS}"
			;;
		$RPL_ENDOFMOTD)
			echo "JOIN ${nm_channel}"
			;;
		*)
			echo "${IRC_PARAMS[*]}" 1>&2
	esac
}

function on_timeout {
  if [[ -f "$shome/tmp/input.txt" ]]; then
    cat "$shome/tmp/input.txt"
    rm -f "$shome/tmp/input.txt"
  else
    date 1>&2
  fi
}
